sudo: false
language: ruby
rvm:
- 2.3
- 2.4
- 2.5
- jruby-9.0
before_install: gem update --system; gem install bundler
cache: bundler
matrix:
  allow_failures:
    - rvm: jruby-9.0
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bundle exec rspec --exclude-pattern "spec/integration_spec.rb"; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bundle exec rspec; fi'
  - bundle exec rubocop -c .rubocop.yml --force-exclusion
