sudo: false
language: ruby
rvm:
- 2.3.7
- 2.4.4
- 2.5.1
- jruby-9.0
before_install: gem install bundler -v 1.16.1
cache: bundler
matrix:
  allow_failures:
    - rvm: jruby-9.0
script:
  - bundle exec rubocop
  - bundle exec rspec
